### PR TITLE
Testing To Do list: part 1 and part 2

### PR DESCRIPTION
**Pull request by mulugithub**
**Hello 🤝 CR**

_This PR, show apply jest to test my previous todo list app_

### Project requirements

**Part 1**

- [ ]  Use jest framework for testing.
- [ ]  Create a test file ([..].test.js) for a file containing the add item and delete item functions that you want to test.
- [ ]  Take a look at each of these functions. Are they pure functions? If the answer is "yes" then writing tests for them should be straightforward. Some of those functions however will update localStorage and manipulate the DOM. For those, you will need to use mocks:
- [ ]  Mock a storage object to "imitate" localStorage operations (only if you are using jest < 24.x, in newer versions localStorage is mocked automatically).
- [ ]  Mock HTML to test if add/delete functions add or remove exactly one
- [ ] element to/from the list in the DOM.
- [ ]  Make sure you group your tests using the describe() method.

**Part 2**

- [ ] Use jest framework for testing.
- [ ] Create a test file(s) ([..].test.js) for a file(s) containing the following functions:
    - [ ] a function for editing the task description.
   - [ ] a function for updating an item's 'completed' status.
   - [ ] the "Clear all completed" function.
- [ ] Use the mock storage object you have created in Part 1 of this project to mock the localStorage updates.
- [ ] Mock the HTML elements to test DOM manipulation functions.
- [ ] Make sure you group your tests using the describe() method.

**Optional requirement**

 Add a --coverage flag to your test script in package.json. That way you will see the percentage coverage of your application code every time you run a test:

### CODE REVIEW

**Review by joskalenda — APPROVED** [review]
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @mulugithub , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
|  |

### Highlights
✅ ... Green test
✅ ... Readme file

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ademibowale — COMMENTED** [review]
Hi @mulugithub , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
-  Green test
- a function for updating an item's 'completed' status.✔️ 

- Descriptive Readme file ✔️ 
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️






- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ademibowale** [comment]
@mulugithub unfortunately I mistakenly approve this PR ,because you submitted 2 project on one PR ,one Pull request is mainly for one project it's wrong to submit different project on one pull request that's an invalid, consequently your project has to be invalidated but I didn't notices this earlier before I approve which goes against code review quality control rules ,please next time dont do this such again it's not best practices to submit different project on just one PR .kindly take this as correction incase next time.

Happy coding .

**Comment by mulugithub** [comment]
I would like thank you for advice

**Pull request merged**
